### ISSUE TITLE
Implement the edit method?

### ISSUE THREAD

**Issue by BlogProgWEB** [stevie-c91/laravel-markdown-editor#1]
Thanks for the solution, but how do you implement the edit method?

**Comment by stevie-c91** [comment]
Hi, i've added edit/update and delete functionality to the repo. Hopefully this helps.

[Commit](https://github.com/stevie-c91/laravel-markdown-editor/commit/096b8cc12ab03bce4130a546f76f7f2b96dfb870)

**Comment by BlogProgWEB** [comment]
Thank you. Works!

I did via "initialValue" and it didn't work
